[package]
name = "api"
version = "0.1.0"
edition = "2021"



[dependencies]
core = { path = "../core" }
utils = { path = "../utils" }
# eframe is the framework that integrates egui for native applications
eframe = "0.24" # Use the latest version